"""Add timezone to org and attendance_submitted_at to session

Revision ID: e5cd7e3ad29c
Revises: d1e41dad1661
Create Date: 2026-07-19 12:05:08.023635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5cd7e3ad29c'
down_revision: Union[str, Sequence[str], None] = 'd1e41dad1661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academy_sessions', sa.Column('attendance_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='UTC'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'timezone')
    op.drop_column('academy_sessions', 'attendance_submitted_at')
    # ### end Alembic commands ###
